public enum TOPIC {
    SELF_HELP,
    TECHNOLOGY, 
    PHILOSOPHY,
    RELIGION,
    POLITICS,
    INTERNATIONAL_RELATIONS,
    COMPUTER_SCIENCE,
    LLM,
    ALGORITHMS,
    MACHINE_LEARNING,
    AI
}
